post/urls.py
from django.urls import path
from . import views

app_name = "post"
urlpatterns = [
    path('' , views.dashboard , name="dashboard"),
    path('post/index' , views.postIndex , name="index"),
    path('post/<int:post_id>/edit' , views.postEdit , name="edit"),
    path('post/<int:post_id>/update' , views.postUpdate , name="update"),
    path('post/create' , views.postCreate , name="create"),
    path('post/store' , views.postStore , name="store"),
    path('post/<int:post_id>/delete' , views.postDelete , name="delete"),
    path('post/<int:post_id>/gallery/<int:gallery_id>/delete' , views.deletePostGalleryImage , name="deletePostGalleryImage"),
    path('post/<int:post_id>/publish/<int:id>/' , views.publishPost , name="publishPost"),
    path('post/list/' , views.postList , name="postList"),
]

post/templates/post/create.html
{% extends "layouts/dashboard.html" %}
{% block content %}
<!--main content start-->

		<div class="form-w3layouts">
            <!-- page start-->
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            Create Post
                            <span class="tools pull-right">
                                <a class="fa fa-chevron-down" href="javascript:;"></a>
                                <!-- <a class="fa fa-cog" href="javascript:;"></a> -->
                                <a class="fa fa-times" href="javascript:;"></a>
                             </span>
                        </header>
                        <div class="panel-body">
                            <form role="form" action="{% url 'post:store' %}" method="post" class="form-horizontal " enctype="multipart/form-data">
                              {% csrf_token %}
                                <div class="form-group  has-warning1 {% if form.errors.title  %} has-error {% else %} has-success {% endif %}">
                                    <label class="col-lg-3 control-label">Title</label>
                                    <div class="col-lg-6">
                                        <input type="text" placeholder="" value="{{form.data.title}}"  name="title" id="f-name" class="form-control">
                                        <p class="help-block "> {{ form.errors.title }} </p>
                                        <!-- {{form.instance.field_name}}  {{ form.field_name.value }} {{form.data.field_name}} -->
                                    </div>
                                </div>

                                
                                <div class="form-group {% if form.errors.content  %} has-error {% else %} has-success {% endif %}">
                                  <label class="col-lg-3 control-label">Content</label>
                                  <div class="col-lg-6">
                                      <textarea type="text"  name="content" placeholder="" id="f-name" class="form-control">{{form.data.content}}</textarea>
                                      <p class="help-block"> {{ form.errors.content }}  </p>
                                  </div>
                                </div>

                                <div class="form-group {% if form.errors.cover  %} has-error {% else %} has-success {% endif %}">
                                  <label class="col-lg-3 control-label">Cover</label>
                                  <div class="col-lg-6">
                                      <input type="file" name="cover" value="{{form.cover.value}}" placeholder="" id="f-name" class="form-control">
                                      <p class="help-block"> {{ form.errors.cover }} </p>
                                  </div>
                                </div>

                                <div class="form-group {% if form.errors.gallery  %} has-error {% else %} has-success {% endif %}">
                                  <label class="col-lg-3 control-label">Gallery</label>
                                  <div class="col-lg-6">
                                      <input type="file"  multiple name="gallery" value="{{form.gallery.value}}" placeholder="" id="f-name" class="form-control">
                                      <p class="help-block"> {{ form.errors.gallery }} </p>
                                  </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-lg-offset-3 col-lg-6">
                                        <button class="btn btn-primary" type="submit">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </section>
                </div>
            </div>
            <!-- page end-->
        </div>
</section>

{% endblock %}

post/templates/post/edit.html
{% extends "layouts/dashboard.html" %}

{% block style %}
<style>
  .card {
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    padding: 5px;
margin: 10px 0px;
widthd: 30% !important;

  }
  
  .card:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
  }
  
  .card a {
    width: 100%;
  }

  .panel-body {
    
display: inline;
  }
  </style>
{% endblock %}
{% block content %}
<!--main content start-->

		<div class="form-w3layouts">
            <!-- page start-->
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            Edit Post
                            <span class="tools pull-right">
                                <a class="fa fa-chevron-down" href="javascript:;"></a>
                                <!-- <a class="fa fa-cog" href="javascript:;"></a> -->
                                <a class="fa fa-times" href="javascript:;"></a>
                             </span>
                        </header>
                        <div class="panel-body">
                            <form role="form" action="{% url 'post:update' post.id %}" method="post" class="form-horizontal " enctype="multipart/form-data">
                              {% csrf_token %}
                                <div class="form-group has-success1 has-warning1 has-error1">
                                    <label class="col-lg-3 control-label">Title</label>
                                    <div class="col-lg-6">
                                        <input type="text" required placeholder="" name="title" value="{{ post.title }}" id="f-name" class="form-control">
                                        <!-- <p class="help-block">Successfully done</p> -->
                                    </div>
                                </div>
                                
                                <div class="form-group has-success1 has-warning1 has-error1">
                                  <label class="col-lg-3 control-label">Content</label>
                                  <div class="col-lg-6">
                                      <textarea type="text" required name="content" placeholder="" id="f-name" class="form-control">{{ post.content }}</textarea>
                                      <!-- <p class="help-block">Successfully done</p> -->
                                  </div>
                                </div>

                                <div class="form-group has-success1 has-warning1 has-error1">
                                  <label class="col-lg-3 control-label">Cover</label>
                                  <div class="col-lg-6">
                                      <img class="post_edit_cover_image" src="{{ post.cover.url }}">
                                      <input type="file" name="cover" value="{{ post.cover }}" placeholder="" id="f-name" class="form-control">
                                      <!-- <p class="help-block">Successfully done</p> -->
                                  </div>
                                </div>

                                <div class="form-group has-success1 has-warning1 has-error1">
                                  <label class="col-lg-3 control-label">Gallery</label>
                                  <div class="col-lg-6">
                                      <input type="file" multiple name="gallery" value="{{ post.cover }}" placeholder="" id="f-name" class="form-control">
                                      <!-- <p class="help-block">Successfully done</p> -->
                                  </div>

                                </div>

                                <div class="form-group">
                                    <div class="col-lg-offset-3 col-lg-6">
                                        <button class="btn btn-primary" type="submit">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </section>
                </div>
            </div>
            <!-- page end-->
        </div>









        <div class="form-w3layouts">
          <!-- page start-->
          <div class="row">
              <div class="col-lg-12">
                  <section class="panel">
                      <header class="panel-heading">
                          Image Gallery
                          <span class="tools pull-right">
                              <a class="fa fa-chevron-down" href="javascript:;"></a>
                              <!-- <a class="fa fa-cog" href="javascript:;"></a> -->
                              <a class="fa fa-times" href="javascript:;"></a>
                           </span>
                      </header>
                      <div class="panel-body">
                          

                        {% for image in post.galleryImages %}
                        <div class="card col-lg-4 col-md-6 col-sm-5">
                          <img src="{{ image.image.url }}" alt="Avatar" style="width:100%; height: 150px;" >
                            <a href="{% url 'post:deletePostGalleryImage' post.id image.id %}" class="btn btn-danger">Delete</a>
                        </div>
                        {% endfor %}

                      </div>
                  </section>
              </div>
          </div>
          <!-- page end-->
      </div>

{% endblock %}

post/templates/post/index.html
{% extends "layouts/dashboard.html" %}
{% block content %}

		<div class="table-agile-info">
 <div class="panel panel-default">
    <div class="panel-heading">
     Post table

     <a href="{% url 'post:create' %}" class="pull-right btn btn-primary">Create Post</a>
    </div>
    <div>
      <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
        <thead>
          <tr>
            <th data-breakpoints="xs">ID</th>
            <th>Title</th>
            <th>Views</th>
            <th>Published</th>
            <th>Created at</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
            {% for post in posts%}
            <tr data-expanded="true">
                <td>{{ post.id }}</td>
                <td>{{ post.title }}</td>
                <td>{{ post.views }}</td>    
                <td>{% if post.publish == 0 %} <strong class="has-error">No</strong>  {% elif post.publish == 1 %} <strong class="has-success">Yes</strong> {% endif %}  </td>    
                <td>{{ post.created_at }}</td>    
                <td>
                    <button class="btn btn-primary">View Details</button>
                    <a href="{% url 'post:edit' post.id %}" class="btn btn-info">Edit</a>
                    <a href="{% url 'post:delete' post.id %}" class="btn btn-danger">Delete</a>
                </td>    
            </tr>
            {% endfor %}
        </tbody>
      </table>
      
      

      <div class="pagination">
        <span class="step-links">
            {% if posts.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            </span>
    
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
                <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>


    
    </div>
  </div>
</div>

{% endblock %}

post/templates/post/publish.html
{% extends "layouts/dashboard.html" %}
{% block content %}

		<div class="table-agile-info">
 <div class="panel panel-default">
    <div class="panel-heading">
     Post table

     <a href="{% url 'post:create' %}" class="pull-right btn btn-primary">Create Post</a>
    </div>
    <div>
      <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
        <thead>
          <tr>
            <th data-breakpoints="xs">ID</th>
            <th>Title</th>
            <th>Views</th>
            <th>Published</th>
            <th>Created at</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
            {% for post in posts%}
            <tr data-expanded="true">
                <td>{{ post.id }}</td>
                <td>{{ post.title }}</td>
                <td>{{ post.views }}</td>    
                <td>{% if post.publish == 0 %} <strong class="has-error">No</strong>  {% elif post.publish == 1 %} <strong class="has-success">Yes</strong> {% endif %}  </td>    
                <td>{{ post.created_at }}</td>    
                <td>
                    <a href="{% url 'post:publishPost' post.id 1 %}" class="btn btn-info">Publish</a>
                    <a href="{% url 'post:publishPost' post.id 0 %}" class="btn btn-danger">UnPublish</a>
                </td>    
            </tr>
            {% endfor %}
        </tbody>
      </table>
      
      

      <div class="pagination">
        <span class="step-links">
            {% if posts.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            </span>
    
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
                <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>


    
    </div>
  </div>
</div>

{% endblock %}